### ISSUE TITLE
请问为什么sac-per-her 算法代码里没有value network构建和loss呢？

### ISSUE THREAD

**Issue by minoshiro1** [kaixindelele/DRLib#12]
当我尝试train-torch结合sac-per时，发现里面并没有关于value function的相关实现，只有q network和actor network， 这样也行吗？

**Comment by kaixindelele** [comment]
PER垃圾，不用试了，效果不好，还慢

**Comment by minoshiro1** [comment]
谢谢，但其实我主要是想问为什么sac里面没有value network定义啊？

**Comment by kaixindelele** [comment]
SAC, TD3, DDPG里面不都没有v网络么？

**Comment by minoshiro1** [comment]
哎？我看SAC都是用V网络 Q网络 和Policy网络呀？ 不用V也行嘛？
