### ISSUE TITLE
there is a error when I try to plot the performance curve.

### ISSUE THREAD

**Issue by red-tie** [kaixindelele/DRLib#2]
the detail of the error is shown in the following
![image](https://user-images.githubusercontent.com/45032766/109377913-4db05380-7909-11eb-8575-77b80c7f5673.png)

**Comment by kaixindelele** [comment]
Fisrtly, you need check your pycharm.
![image](https://user-images.githubusercontent.com/28528386/109378055-7127ce00-790a-11eb-99d7-70dce61562e7.png)

Secondly, if you plot figures with ssh, you must add:
```python
plt.switch_backend('agg')
```
before plt.figure() in plot.py file, like the following:
![image](https://user-images.githubusercontent.com/28528386/109378120-ef847000-790a-11eb-9631-3bf6f3d329d9.png)

**Comment by red-tie** [comment]
tks, the problem has been solved
