### ISSUE TITLE
为什么说：存的时候替换目标其实不合适呀，数据变化如何受限，正确的存放方法是？

### ISSUE THREAD

**Issue by luo-li-ba-suo** [kaixindelele/DRLib#4]
看到有些地方是一个episode结束之后再用新目标生成her数据，继而存放her数据，是不是有什么不一样

**Comment by kaixindelele** [comment]
是这样的，关于her的buffer数据存储。
有两种实现方案：
1.我采用的：每和环境交互一个episode，将整个episode的transitions做re-goal的处理，每个transition生成四份re-goal的transition，加上一份本身，存到一个普通的FIFO（先入先出）buffer中；这个的优点在于后面的buffer可以借用普通的，net采样数据的函数都不用改；不好的地方在于，原始的episode的顺序信息被打乱了，普通的buffer-size也要相应的扩大（4+1）倍；
2.另外一种方式：创建一个新的数据结构，每交互一个episode的transitions都放一块儿；每次采样的时候，先随机选出episode-index，然后再选transition-index，整个的结构就特别复杂~
最终的效果是一样的，因为每一个transition，被re-goal和采样期望是一致的~
强化的性能也是一样的，我目前采用的是第一种。

**Comment by luo-li-ba-suo** [comment]
牛！谢谢啦
