### ISSUE TITLE
plot

### ISSUE THREAD

**Issue by tinmodeHuang** [kaixindelele/DRLib#5]
could you upload some data to plot figure below(especially shaded regions)? the installation takes too much time, it is hard for me to get that license
![image](https://user-images.githubusercontent.com/65896325/117388632-ac9fd380-af1d-11eb-9019-15eed32fe072.png)

**Comment by kaixindelele** [comment]
好几个人确实都遇到了这个问题，我已经上传了两个示例数据，你可以下载试试了.

有问题可以及时issues沟通~

**Comment by tinmodeHuang** [comment]
数据在哪，我的网不好，是否足以画出阴影区域呢

**Comment by kaixindelele** [comment]
https://github.com/kaixindelele/DRLib/tree/main/spinup_utils/plot_demo_files

这个文件夹中，应该是可以的，你先自己调一下试试，应该是可以画出一条带阴影的曲线

**Comment by tinmodeHuang** [comment]
想问一下，tsplot中参量unit没有指定哪一列的话，图就画不出来。那要指定的话，指定列的数据要符合什么要求，该列的数值对结果有什么影响吗
