### ISSUE TITLE
关于DRLib在gym的不同环境的适用性

### ISSUE THREAD

**Issue by Spartan859** [kaixindelele/DRLib#6]
请问是只要在arguments.py中修改环境名字和参数就能适配不同环境吗？

我改用了Pendulum-v0环境，但好像会报错numpy数组下标的错，

说只有整数，slice(:)……可以作为下标。我稍后可以发个具体报错

**Comment by kaixindelele** [comment]
我的arguments的默认参数是针对HER算法封装的，适合goal-based的环境，类似于pendulum-v0这种环境，需要自己debug一下，才能正常运行。
首先参数中的her要false，要修改obs-->state的转换，这些东西还是挺麻烦的~
强化算法+基础的GYM环境的主函数，你可以参考原版的spinningup的例程，自己写一个应该也不麻烦，我不太想单独写了~

**Comment by Spartan859** [comment]
明白了，谢谢大佬！
