### ISSUE TITLE
请问td3多进程中的代码

### ISSUE THREAD

**Issue by namjiwon1023** [kaixindelele/DRLib#7]
DRLib/algos/pytorch/td3_sp/MPI_td3_per_her.py 

line 146    mpi_avg_grads(self.ac.v)   # 请问 这个代码是正确的嘛  ac.q1 ,  ac.q2 ,  q_params

或许说self.ac.v 在那里定义了嘛

谢谢

**Comment by kaixindelele** [comment]
torch版本的多进程没测试好！
TF版本的DDPG是比较靠谱的，torch版本的我先删掉了...

**Comment by namjiwon1023** [comment]
哦 好的 谢谢
