### ISSUE TITLE
训练结果显示

### ISSUE THREAD

**Issue by ZHQ-air** [kaixindelele/DRLib#8]
您好，感谢您的代码分享！我在学习您的代码，正在学习代码中spinningup_utils中绘制RL仿真结果的部分，我跑完了三个随机种子的实验，然后运行命令：  `python spinning_utils/plot.py ./HER_DRLib_exps --smooth=3 --count`，结果在一个图中分别出现了三个随机种子的曲线；

然后我运行命令`python spinning_utils/plot.py ./HER_DRLib_exps --smooth=3` 想让代码绘制出三个随机种子的平均曲线（有阴影效果的那种），曲线却显示不出来，请问这是怎么回事啊？

**Comment by RLDSCVAE** [comment]
把路径再往下面放一层试试，你的实验路径名也不用完全输完，输入一半就行
`python spinning_utils/plot.py ./HER_DRLib_exps/your_exp_name... --smooth=3`

**Comment by ZHQ-air** [comment]
我的实验路径名是这样的
在HER_DRLib_exps/2021-09-29_HER_mpi19_random_HSRU-AC_BipedalWalker-v3分别对应三个随机种子的数据文件夹。

我把路径再往下面放一层试了一下，还是不能正常出现三个随机种子的带阴影的平均曲线

**Comment by ZHQ-air** [comment]
不知道是不是因为我只运行了一个算法的原因，我再在三个随机种子下运行另外一个算法试下
